version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  
  python:
    tty: true
    image: erikaosgue/spotify_datapipeline 
    user: root
    container_name: python
    volumes:
        - ${HOST_DIR}:/usr/src/app
    ports:
      - '5000:5000'
    depends_on: 
      - kafka
    environment:
        CLIENT_ID: ${CLIENT_ID}
        SECRET_ID: ${SECRET_ID}

  spark:
    image: erikaosgue/spark 
    user: root
    container_name: master_spark
    volumes:
        - ${HOST_DIR_SPARK}:/opt/bitnami/spark/work
    ports:
      - '8080:8080'
      - '8888:8888'
    command: tail -F anything
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on: 
      - kafka

  spark-worker:
    image: erikaosgue/spark 
    container_name: worker_spark_1
    command: tail -F anything
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
