version: '3'

services:
  zookeeper
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      #KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  python:
    tty: true
    image: erikaosgue/spotify_datapipeline
    user: root
    container_name: python
    volumes:
        - /home/erikaosgue/erika_work/data_engineering/CREATING_DATAPIPELINES/Spotify_datapipeline/kafka-python/src:/usr/src/app
    ports:
      - '5000:5000'

